apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lunary-secrets
  namespace: lunary
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: lunary-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: LUNARY_JWT_SECRET
    - secretKey: database-url
      remoteRef:
        key: LUNARY_DATABASE_URL
